import Head from 'next/head';
import Link from 'next/Link';
import { useUser } from '@auth0/nextjs-auth0';
import Header from '../components/Header';

export default function Home() {
	const { user, error, isLoading } = useUser();

	if (isLoading) return <div>Loading...</div>;
	if (error) return <div>{error.message}</div>;

	if (user) {
		return (
			<div>
				<Head>
					<title>LinkedIn</title>
					<meta
						name="description"
						content="Generated by create next app"
					/>
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Header />
				<Link href="/api/auth/login">
					<a>Login</a>
				</Link>
				<div>
					Welcome {user.name}!{' '}
					<Link href="/api/auth/logout">
						<a>Logout</a>
					</Link>
				</div>
				<Link href="/home">
					<a>Home</a>
				</Link>
				;
			</div>
		);
	}
}
